changelog:
  categories:
    - title: Features
      labels: [enhancement, feature]
    - title: Fixes
      labels: [bug, fix]
    - title: Changes
      labels: [chore, refactor, dependencies]
    - title: Build
      labels: [ci, build]
    - title: Other
      labels: ['*']
